name: Publish Blog to Dev.to, Medium, and Hashnode

on:
  push:
    paths:
      - blog.md  # Trigger only when blog.md changes

jobs:
  publish_blog:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Publish blog post
        uses: Prachi-Jamdade/blog-publisher@main
        with:
          markdown_file: blog.md
          devto_api_key: ${{ secrets.DEVTO_API_KEY }}
          medium_token: ${{ secrets.MEDIUM_INTEGRATION_TOKEN }}
          hashnode_api_key: ${{ secrets.HASHNODE_API_KEY }}
